[workspace]
members = ["crates/wle-core", "crates/wle-cli", "crates/wle-gui"]
resolver = "2"
default-members = ["crates/wle-core", "crates/wle-cli", "crates/wle-gui"]

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["Jari Ravantti"]
